# Site settings
title: HypeGuides
tagline: Hypenotic Handbook
email: lionel@hypenotic.com
description: The toolkits and guidelines that power Hypenotic projects.
version: 1.0
#baseurl: "/handbook" # the subpath of your site, e.g. /blog/
#url: "http://hypenotic.github.io/handbook" # the base hostname & protocol for your site
twitter_username: lionelmann
github_username:  lmann

# Build settings
markdown: redcarpet

data_source: ./_data

readtime:		true
wpm:			200
repo: hypenotic/handbook
branch: gh-pages

#Exclude
exclude: [node_modules, gulpfile.js, bower.json, package.json]